#!/usr/bin/env bash

set -e

echo "===> Bootstrapping..."
script/bootstrap --quiet

echo "===> Setting test environment variables..."
for testvar in LOGIN PASSWORD TOKEN CLIENT_ID CLIENT_SECRET
do
  octokitvar="OCTOKIT_TEST_GITHUB_${testvar}"
  if [[ -z "${!octokitvar}" ]]; then
      echo "Please export ${octokitvar}";
  fi
done

export OCTOKIT_SILENT=true

echo "===> Running tests..."
(unset OCTOKIT_LOGIN; unset OCTOKIT_ACCESS_TOKEN; nosetests)
